### ISSUE TITLE
Readme update: howto rebuild without "switch"

### ISSUE THREAD

**Issue by osv** [kenranunderscore/dotfiles#1]
I like you how organized code. Can you update readme, how can you update only home profile via home-manager.
Following command will switch nixos and update grub every time:
```
nixos-rebuild switch --use-remote-sudo --flake ~/dotfiles
```

**Comment by osv** [comment]
Smtg like this
```
nix shell --verbose ".#nixosConfigurations.$HOST.config.home-manager.users.$USER.home.activationPackage" --command home-manager-generation
```

**Comment by kenranunderscore** [comment]
Thank you for the suggestion! I thought something like this was possible but never bothered to look (I routinely call garbage collection, including system generations). Now that I know it, I'll surely incorporate it (added a handy alias for it as well) into my workflow.
